### PR TITLE
docs(readme): building from source

### LINKED ISSUE #23: Request: instructions on how to build from source
Awesome project!
Naturally, peeps are a bit wary to run precompiled binaries and then grant access to the interwebs and their bank accounts, simultaneously.
Possible to add a slice of text somewhere with pointers on how to build & install locally?

### PR DESCRIPTION
**Pull request by engvik**
Adds steps for building from source.

Closes #23

### CODE REVIEW

**Comment by engvik** [comment]
@haakonstorm is this sufficient?

**Comment by paalbra** [comment]
Mention version requirement?

It won't build on debian latest with go 1.11.6:
```
# github.com/engvik/sbanken-cli/internal/cli
internal/cli/cli.go:49:23: undefined: os.UserConfigDir
note: module requires Go 1.15
```

It does build on ubuntu latest with go 1.13.8, which seems weird after seeing the error on debian?

**Comment by engvik** [comment]
> Mention version requirement?

:+1: 

> It does build on ubuntu latest with go 1.13.8, which seems weird after seeing the error on debian?

Yeah, it because the use of `gomodules` aren't the default in go1.11, I think it will build if you set `GO111MODULES=on`. I'll describe it a bit more in detail.

**Comment by haakonstorm** [comment]
This might be unrelated, but:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13821db]

goroutine 1 [running]:
github.com/engvik/sbanken-cli/internal/sbanken.(*Connection).getAccountIDFromAlias(0x00beef, 0x00beef, 0x00beef, 0x00beef, 0x00beef)
	/home/lars/dev/priv/sbanken-cli/internal/sbanken/sbanken.go:145 +0x00beef
github.com/engvik/sbanken-cli/internal/sbanken.(*Connection).getAccountID(0x00beef, 0x00beef, 0x00beef, 0x00beef, 0x00beef, 0x00beef)
	/home/lars/dev/priv/sbanken-cli/internal/sbanken/sbanken.go:96 +0x00beef
github.com/engvik/sbanken-cli/internal/sbanken.(*Connection).ListTransactions(0x00beef, 0x00beef, 0x00beef, 0x00beef)
	/home/lars/dev/priv/sbanken-cli/internal/sbanken/transactions.go:17 +0x00beef
github.com/urfave/cli/v2.(*Command).Run(0x00beef, 0x00beef, 0x00beef, 0x00beef)
	/home/lars/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x00beef
github.com/urfave/cli/v2.(*App).RunContext(0x00beef, 0x00beef, 0x00beef, 0x00beef, 0x00beef, 0x00beef, 0x00beef, 0x00beef)
	/home/lars/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x00beef
github.com/urfave/cli/v2.(*App).Run(...)
	/home/lars/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/home/lars/dev/priv/sbanken-cli/cmd/sbanken/main.go:28 +0x00beef
```

on invoking with 

```
λ envchain sbanken ~/Downloads/sbanken ta --id PRIVAT --sd 2020-01-01 --ed 2020-02-02
```

This is with the stock `release` binary; seems like someone named `lars` gifted us a compiled home folder path? :-)

(check out`envchain`, tiny very useful tool for storing secrets in userland keychains, both on macos and linux)

My `~/.config/sbanken/config.yaml` looks like this:

```
λ cat ~/.config/sbanken/config.yaml 

account-aliases:
  393BE97B0C966713F13E59C7C7BD985C: "PRIVAT"
``` 

I used two leading spaces in the YAML from habit; that seems to deviate from the docs?

**Comment by engvik** [comment]
Interesting, what system are you on?

**Comment by engvik** [comment]
@haakonstorm I was able to reproduce and it should be fixed in #26. I suspect you might be on MacOS and haven't passed the location of the config file, see [default locations](https://github.com/engvik/sbanken-cli#configuration-file).

**Comment by haakonstorm** [comment]
I'm on macOS (big sur, M1) and follow the `$XDG_CONFIG_HOME/sbanken/config.yaml` paradigm; perhaps we could look there as well, on darwin environments?

**Comment by engvik** [comment]
Default config directories are currently handled [by the standard library](https://pkg.go.dev/os#UserConfigDir), no idea why they don't consider `$XDG_CONFIG_HOME` on darwin.

**Comment by haakonstorm** [comment]
The go standard library is in error.

When one author a command line tool on [modern] unix, config files by [the convention](https://standards.freedesktop.org/basedir-spec/latest/index.html) is stuffed in `$XDG_CONFIG_HOME`.

When you author a GUI tool on [modern] unix, on the other hand, you'd use `/usr/lib/X11/app-defaults/` or something.

Similarly, when one author a GUI tool on macOS, conformance to the various macOS specifics are neccessary for Steve to still rest in peace. Config files (+ transient runtime data, caches, et al) for macOS GUI apps live in various `/Library` domains (`/Network/Library`, `/System/Library`, `/Library`, `~/Library`).

But, the `sbanken-cli` tool is not a macOS specific GUI tool. 
Nor is it a UNIX GUI tool! 
It's a plain, good-ol', UNIX command line tool. 
Which is why we love it so much.

So, if the tool build chain pay any attention to anything macOS specific, without being a GUI app, a lot of stuff has gone wrong many places along the way. Actually, looking at the stdlib.go source, I realize it needs to be refactored and all references to `darwin` there must be moved to some other go library. When you read the code, you see there is special care taken if and only if compilation happens on Windows. This is natural as Windows in fact *needs* special care, not only because it is the cancer tumor of humandkinds coordinated effort to further the very real science of software development, it also sucks *tremendously salty* balls. BUT! On macOS, anything related to the command line, anything that even *slightly* has *any* scent of POSIX whatsoever, must just bulldoze forward as a screaming parade of every single oddity UNIX has ever born. No regard must be given to whatever Apple has engineered as a superset on top of UNIX. Doing so undermines both progress of the UNIX ecosystem *and* anything Apple, simultaneously.

**Comment by engvik** [comment]
Yeah, it's trivial to implement and I'd be happy to do so.

You might find [this discussion](https://github.com/golang/go/issues/29960) interesting, and particularly [this comment](https://github.com/golang/go/issues/29960#issuecomment-505321146).

**Comment by haakonstorm** [comment]
And sorry for the rant. It was meant to be funny. 

Which it apparently failed to be. Which in itself *is* kinda funny.

Thanks for the links to the background info; a lot of really interesting back and forth in there. I had no idea. Seems they concluded the ship has left - to the effect of not introducing what would be a pretty serious regression. Effectively leaving `cli` tools to choose which way to lean.

**Comment by engvik** [comment]
Haha, no worries, wasn't sure if you actually was ranting or only joking around :stuck_out_tongue: Was in a bit of a hurry when I replied as well.
